apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-web  
  namespace: nm   
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  locust-web
  template:
    metadata:
      labels:
        app:  locust-web
    spec:
      containers:
      - name: locust-web
        image: dockerhouse.azurecr.io/locusttest:1.0.0         
        ports:
        - containerPort: 8089
        volumeMounts:
            - mountPath: /mnt/locust/locustfile.py
              subPath: locustfile.py
              name: locust-scripts
      imagePullSecrets:
      - name: topsecretregistryconnection
      volumes:
      - name: locust-scripts
        configMap:
          name: scripts-cm
---
kind: Service
apiVersion: v1
metadata:
  name: locust-web-service   
  namespace: nm
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8089      
  selector:
    app:  locust-web
