apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-cm
data:
  locustfile.py: |
    import random
    from locust import HttpUser, task, between

    class QuickstartUser(HttpUser):
        wait_time = between(5, 9)

        @task
        def index_page(self):
            for i in range(3):      
            #    self.client.get("/querydetails?id=%i" % (i+1), name="/querydetails?id=[id]")
                 self.client.get("/films/58611129-2dbc-4a81-a72f-77ddfc1b1b49")
